import React from 'react';
import { Sparkles, Lightbulb } from 'lucide-react';

const AISummary: React.FC = () => {
  return (
    <div className="bg-white rounded-xl border border-gray-100 shadow-sm overflow-hidden h-full flex flex-col">
      <div className="p-6 border-b border-gray-50 flex items-center justify-between bg-gradient-to-r from-purple-50/50 to-white">
        <div className="flex items-center space-x-2">
          <div className="bg-purple-100 p-1.5 rounded-lg">
            <Sparkles className="text-purple-600" size={18} />
          </div>
          <h3 className="text-lg font-bold text-gray-900">AI Executive Summary</h3>
        </div>
        <div className="flex items-center space-x-1.5 px-2.5 py-1 bg-green-50 text-green-700 rounded text-xs font-semibold border border-green-100">
          <Sparkles size={12} />
          <span>Generated by AI</span>
        </div>
      </div>
      
      <div className="p-6 flex-1 flex flex-col justify-between">
        <ul className="space-y-4 text-sm text-gray-700">
          <li className="flex items-start">
            <span className="w-1.5 h-1.5 rounded-full bg-purple-500 mt-1.5 mr-3 shrink-0"></span>
            <p>Revenue grew by <strong className="font-semibold text-gray-900">13%</strong> compared to the previous period, driven by strong performance in Electronics and the North region.</p>
          </li>
          <li className="flex items-start">
            <span className="w-1.5 h-1.5 rounded-full bg-purple-500 mt-1.5 mr-3 shrink-0"></span>
            <p>The <strong className="font-semibold text-gray-900">West region</strong> contributes <strong className="font-semibold text-gray-900">46% of total profits</strong>, making it the key growth driver.</p>
          </li>
          <li className="flex items-start">
            <span className="w-1.5 h-1.5 rounded-full bg-purple-500 mt-1.5 mr-3 shrink-0"></span>
            <p>Furniture has high sales volume but the <strong className="font-semibold text-gray-900">lowest profit margin at 7.2%</strong>, indicating potential cost or discounting issues.</p>
          </li>
          <li className="flex items-start">
            <span className="w-1.5 h-1.5 rounded-full bg-purple-500 mt-1.5 mr-3 shrink-0"></span>
            <p>Electronics remains the most profitable category with <strong className="font-semibold text-gray-900">₹6.2 Cr</strong> in profit.</p>
          </li>
        </ul>
        
        <div className="mt-6 bg-orange-50/50 border border-orange-100 rounded-xl p-5">
          <div className="flex items-center space-x-2 mb-2 text-orange-800">
            <Lightbulb size={18} className="text-orange-500" />
            <h4 className="font-bold text-sm">Key Recommendation</h4>
          </div>
          <p className="text-sm text-orange-900 leading-relaxed font-medium">
            Increase advertising for electronics in North India and review pricing strategy for furniture to improve margins.
          </p>
        </div>
      </div>
    </div>
  );
};

export default AISummary;
